// Graph (network) layout (v57+)
process.env.AUDIOGRAPH_PARTICLE_BUILD=process.env.AUDIOGRAPH_GRAPH_BUILD||'versions/audiograph_57.html';
const { open, wav, sine, kicks, load } = require('./audio-common.cjs');
const assert=(c,m)=>{if(!c){console.error('FAIL: '+m);process.exit(1)}console.log('ok - '+m)};
(async()=>{const t=await open({viewport:{width:1280,height:800}});const {page,errors}=t;
 const tone=wav([[20,s=>kicks(0.6)(s)+sine(220,0.2)(s)+sine(1760,0.06)(s)]],'s.wav');
 await load(page,{name:tone.name,mimeType:tone.mimeType,buffer:tone.buffer});
 assert(await page.locator('[onclick^="setLayout(\'graph\'"]').count()===1,'Graph layout button exists');
 await page.evaluate(()=>{particlesOn=false;setLayout('graph',document.querySelector('[onclick^="setLayout(\'graph\'"]'));if(!playing)togglePlay()});
 assert(await page.locator('#layoutOpts_graph').isVisible(),'Graph options panel visible');
 assert(await page.evaluate(()=>graphMap==='along'&&graphTick==='along'),'defaults along/along');
 await page.waitForTimeout(500);
 const i1=await page.evaluate(()=>agGraph.info());
 assert(i1.nodes===160,'node count follows slider ('+i1.nodes+')');
 assert(i1.loose>10&&i1.isolated>5,'loose/isolated notes present '+i1.loose+'/'+i1.isolated);
 assert(i1.maxDeg>=10&&i1.edges>120,'hubs form ('+i1.maxDeg+' max links, '+i1.edges+' edges)');
 await page.waitForTimeout(600);
 const i2=await page.evaluate(()=>agGraph.info());
 assert(JSON.stringify(i1.pos)!==JSON.stringify(i2.pos),'nodes move between frames');
 await page.evaluate(()=>{document.getElementById('pGraphNodes').value=80;upP()});await page.waitForTimeout(200);
 assert((await page.evaluate(()=>agGraph.info())).nodes===80,'node slider rebuilds the network');
 const e0=(await page.evaluate(()=>agGraph.info())).edges+'/'+(await page.evaluate(()=>agGraph.info())).maxDeg;
 const sd=await page.evaluate(()=>graphSeed);await page.evaluate(()=>graphShuffle());
 const s2=await page.evaluate(()=>[graphSeed,agGraph.info().pos[0]]);
 assert(s2[0]!==sd,'shuffle changes the seed');
 const ink=()=>page.evaluate(()=>{const c=document.getElementById('frameCv'),x=document.createElement('canvas');x.width=200;x.height=125;const g=x.getContext('2d');g.drawImage(c,0,0,200,125);const d=g.getImageData(0,0,200,125).data;let n=0;for(let i=0;i<d.length;i+=4)if(d[i]+d[i+1]+d[i+2]>90)n++;return n});
 await page.waitForTimeout(400);const n=await ink();assert(n>80,'graph renders ink ('+n+')');
 await page.evaluate(()=>{setGraphMap('shapes');setGraphTick('across');document.getElementById('pGraphHubs').value=8;document.getElementById('pGraphBloom').value=66});
 const st=await page.evaluate(()=>JSON.stringify(getState()));const seedS=await page.evaluate(()=>graphSeed);
 await page.evaluate(()=>{setGraphMap('along');setGraphTick('along');graphSeed=5;document.getElementById('pGraphHubs').value=2;document.getElementById('pGraphBloom').value=0});
 await page.evaluate(s=>applyState(JSON.parse(s)),st);
 assert(await page.evaluate(s=>graphMap==='shapes'&&graphTick==='across'&&graphSeed===s&&+document.getElementById('pGraphHubs').value===8&&+document.getElementById('pGraphBloom').value===66,seedS),'map/tick/seed/sliders restored via state');
 const cnt=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=500;const g=c.getContext('2d');const z=new Array(120).fill(0),r=[];
   for(const b of [0,100]){document.getElementById('pGraphBloom').value=b;let L;for(let i=0;i<120;i++)L=agGraph.draw(g,800,500,z,{height:1,thick:1,glow:0},false);r.push(L.length)}return r});
 assert(cnt[1]<cnt[0]*0.5,'bloom hides links at silence ('+cnt[1]+' < '+cnt[0]+')');
 const ky=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=250;const g=c.getContext('2d');document.getElementById('pGraphPulse').value=100;let mx=0;
   for(let i=0;i<90;i++){globalFrame++;const v=new Array(120).fill(0).map((_,k)=>k<15?(i%30<3?1:.05):.2);agGraph.draw(g,400,250,v,{height:1,thick:1},false);mx=Math.max(mx,agGraph.info().kick)}return mx});
 assert(ky>0.05,'bass kicks pulse the graph ('+ky.toFixed(3)+')');
 assert(errors.length===0,'no page errors '+JSON.stringify(errors));
 await page.screenshot({path:'/tmp/ap/graph57.png'});
 await t.close?.();process.exit(0)})();
